### ISSUE TITLE
关于自动编号后制表符与自动编号的小疑问

### ISSUE THREAD

**Issue by northword** [xiongfly/Huazhong-agricultural-university-thesis-csl#1]
> 修复了引文后存在一个制表符的bug。
> 删除了引文前的编号方便使用自动编号对齐。 

参考文献表序号后的制表符是为了保证序号后的内容换行后仍保持对齐，如果没有自动对齐，可以向原仓库提 issue。

引文前的编号由CSL生成，且保持tab，可以完成自动对齐，如果序号增加了数量级，需要重新换一下样式，换成别的再换回来，这时候 Zootero 会刷新制表符长度，这属于 Zotero 的不完善地方。

**Comment by xiongfly** [comment]
![image](https://github.com/xiongfly/Huazhong-agricultural-university-thesis-csl/assets/130461183/4f4d3431-f2fe-4a99-aee8-98fac53b31cb)
抱歉我描述的不够准确，原作者的CSL是每个题录后一个对齐的制表符（这在某些情况下会导致多出来空的一行）。而编号需要制表符的恰恰不是而是空格，我研究了半天不知道怎么把这里的空格换成制表符，索性就把编号删除了，使用word自动编号。最后样式显示如下图。
![image](https://github.com/xiongfly/Huazhong-agricultural-university-thesis-csl/assets/130461183/b714400a-a028-4fba-a497-95523e595b8a)

**Comment by northword** [comment]
May be fixed by https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/199

**Comment by xiongfly** [comment]
谢谢大佬，能不能把中文文献里面的标点换成全角而英文不变，我太菜了搞半天都不行😂

**Comment by northword** [comment]
在此跟进：https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/pull/200
